// 预约订单质检
export const GET_RESERVATION_LIST = 'GET_RESERVATION_LIST'
export const GET_RESERVATION_UNQUALIFYLIST = 'GET_RESERVATION_UNQUALIFYLIST'
export const GET_APPEAL_FORM = 'GET_APPEAL_FORM'
export const GET_MEDIA_USERS = 'GET_MEDIA_USERS'
export const GET_VOL_USERS = 'GET_VOL_USERS'
export const GET_PLATFORM_LIST = 'GET_PLATFORM_LIST'
export const GET_QC_STATUS_LIST = 'GET_QC_STATUS_LIST'
export const UPDATE_UNQUALIFY_CHECKBOX_STATUS = 'UPDATE_UNQUALIFY_CHECKBOX_STATUS';
export const GET_RESERVATION_UNQUALIFYALLLIST = 'GET_RESERVATION_UNQUALIFYALLLIST'
export const RESERVATION_CHANGE_DISABLED = 'RESERVATION_CHANGE_DISABLED'
export const RESERVATION_CHANGE_APPEALDISABLED = 'RESERVATION_CHANGE_APPEALDISABLED'
export const GET_IMAGE_URL = 'GET_IMAGE_URL'
export const GET_MODIFY_COMPLAINT = 'GET_MODIFY_COMPLAINT'
export const GET_APPEAL_UNQUALIFY_DATA = 'GET_APPEAL_UNQUALIFY_DATA'
export const RESERVATION_IMAGE_PATH = 'RESERVATION_IMAGE_PATH'
export const RESERVATION_CHANGE_EDITDISABLED = 'RESERVATION_CHANGE_EDITDISABLED'
export const TRANSFORM_ROLEID = 'TRANSFORM_ROLEID'
export const RESETACTIVEINSPECTIONDATA = 'RESETACTIVEINSPECTIONDATA'

//只读弹框出现 执行内容 结果，数据截图 actionType
export const GET_EXECUTEDATA_SUCCESS = 'GET_EXECUTEDATA_SUCCESS'
export const GET_EXECUTEDATA_ERROR = 'GET_EXECUTEDATA_ERROR'
