export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const ORDER_EXCEL_LIST = 'ORDER_EXCEL_LIST'
export const ORDER_TEMP_LIST = 'ORDER_TEMP_LIST'
export const FILED_LIST = 'FILED_LIST'
export const FILEDAMEND_DETAIL = 'FILEDAMEND_DETAIL'
export const DELETE_FIELD = 'DELETE_FIELD'
export const EDIT_FIELD = 'EDIT_FIELD'
export const ADD_FIELD = 'ADD_FIELD'
export const TEMP_LIST = 'TEMP_LIST'
export const DEL_TEMP = 'DEL_TEMP'
export const ADD_TEMP = 'ADD_TEMP'
export const EDIT_TEMP = 'EDIT_TEMP'
export const TEMP_DETAIL = 'TEMP_DETAIL'
export const TEMP_ALL_DETAIL = 'TEMP_ALL_DETAIL'
export const GET_OPTIONS_SUCCESS = 'GET_OPTIONS_SUCCESS'
export const GET_ORDER_FIELDS_SUCCESS = 'GET_ORDER_FIELDS_SUCCESS'
export const UPDATE_ORDER_FIELDS = 'UPDATE_ORDER_FIELDS'
export const UPDATE_FIELD_NAME = 'UPDATE_FIELD_NAME'
export const GET_SOURCERULES_LIST = 'GET_SOURCERULES_LIST'
export const DELETE_SOURCE_RULES = 'DELETE_SOURCE_RULES';
export const ADD_SOURCE_RULES = 'ADD_SOURCE_RULES';
export const UPDATE_SOURCE_RULES = 'UPDATE_SOURCE_RULES';
export const GET_NAVGROUP_LIST = 'GET_NAVGROUP_LIST'
export const SHOW_FILTERFROM_SUCCESSHINT = 'SHOW_FILTERFROM_SUCCESSHINT'
export const UPDATE_SOURCERULES = 'UPDATE_SOURCERULES'
export const GET_SOURCERULES_DETAIL = 'GET_SOURCERULES_DETAIL'
export const TRANS_SOURCERULES_PARAM = 'TRANS_SOURCERULES_PARAM'
// 资源类型
export const GET_SOURCETYPE_LIST = 'GET_SOURCETYPE_LIST'
export const GET_SOURCERULE_LIST = 'GET_SOURCERULE_LIST'
export const ADD_SOURCETYPE = 'ADD_SOURCETYPE'
export const UPDATE_SOURCETYPE = 'UPDATE_SOURCETYPE'
export const DELETE_SOURCETYPE = 'DELETE_SOURCETYPE'
export const GET_SOURCETYPE_DETAIL = 'GET_SOURCETYPE_DETAIL'
export const TRANS_SOURCETYPE_PARAM = 'TRANS_SOURCETYPE_PARAM'
//资源
export const GET_SOURCELIST = 'GET_SOURCELIST'
export const DELETE_SOURCE = 'DELETE_SOURCE'
export const ADD_SOURCE = 'ADD_SOURCE'
export const UPDATE_SOURCE = 'UPDATE_SOURCE'
export const GET_SOURCE_DETAIL = 'GET_SOURCE_DETAIL'
export const TRANS_SOURCE_PARAM = 'TRANS_SOURCE_PARAM'
//导航分类
export const GET_NAVTYPE_LIST = 'GET_NAVTYPE_LIST'
export const DELETE_NAVTYPE = 'DELETE_NAVTYPE'
export const ADD_NAVTYPE = 'ADD_NAVTYPE'
export const UPDATE_NAVTYPE = 'UPDATE_NAVTYPE'
export const GET_NAVTYPE_DETAIL = 'GET_NAVTYPE_DETAIL'
export const TRANS_NAVTYPE_PARAM = 'TRANS_NAVTYPE_PARAM'
//导航
export const GET_NAV_LIST = 'GET_NAV_LIST'
export const DELETE_NAV = 'DELETE_NAV'
export const ADD_NAV = 'ADD_NAV'
export const UPDATE_NAV = 'UPDATE_NAV'
export const GET_NAV_DETAIL = 'GET_NAV_DETAIL'
export const TRANS_NAV_PARAM = 'TRANS_NAV_PARAM'

export const GET_ROLE_LIST = 'GET_ROLE_LIST'  //角色列表
export const ADD_ROLE_TYPE = 'ADD_ROLE_TYPE'  //增加角色
export const DELETE_ROLE_TYPE = 'DELETE_ROLE_TYPE'  //删除角色
export const UPDATE_ROLE_TYPE = 'UPDATE_ROLE_TYPE'  //修改角色


export const ADD_USER_ROLE_TYPE = 'ADD_USER_ROLE_TYPE'  //添加用户角色
export const UPDATE_USER_ROLE_TYPE = 'UPDATE_USER_ROLE_TYPE'  //用户角色修改
export const DELETE_USER_ROLE_TYPE = 'DELETE_USER_ROLE_TYPE'  //用户角色删除
export const GET_ROLE_RELATION_LIST = 'GET_ROLE_RELATION_LIST'  //用户角色关系列表
